### ISSUE TITLE
Prototype Feedback

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Swadge-S2-Devkit#4]
# Silkscreen
 - [x] Replace chevron silkscreen with X/Y silkscreen
 - [x] Add silkscreen for power switch sides
 - [x] Add URL silkscreen "swadge.com/super2023/"
 - [x] Add e-mail silkscreen circuitboards@magfest.org
 - [x] Add version silkscreen (1.0.1)
 - [x] Add A and B button silkscreen
 - [x] Add silkscreen dot or marking or something for UP on the D-Pad to indicate "programming mode button"
 - [x] "Yes these are buttons"

# LEDs
 - [ ] Fix LED placement
 - [ ] Swap LED types

# Kidneys
 - [x] Enlarge holes for kidney mounting. reimport footprint for both main part and PCB
 - [x] Tie all kidney mounting holes to GND, not VCC.
 - [ ] Decide shield location
 - [ ] Either use a thicker kidney (1.6mm) or add another mounting point at the bottom of the controller grip
 - [ ] Pick a kidney!

# Part Placement
 - [x] Move SAO out from under kidney, flip to front of Swadge
 - [x] Rotate start/select 90 degrees, push closer together, move TFT upwards
 - [x] Update TFT part to accommodate either long or short tail, just in case (@cnlohr to email Ronbo)
 - [x] Move power switch up to not hang over the board so much (flush)

# Misc
 - [x] Remove UART pads (nah, let's leave them)
 - [x] Pick a microphone, scrap the other, move it to original location (@cnlohr, you get to pick. My preference is for the larger one to balance the buzzer)
 - [x] Mic pullup needs to be 10k
 - [x] R3 needs to be 10k
 - [x] Remove or shrink button debounce caps
 - [x] Add CC1/CC2 pullups for USB-C power

# BOM
 - [x] Use low-force buttons for A/B (https://lcsc.com/product-detail/Tactile-Switches_XKB-Connectivity-TS-1103S-B-A_C2929546.html is the best I could find)
 - [x] DNP the SAO.
 - [x] R5 has wrong LCSC part #

**Comment by AEFeinstein** [comment]
@cnlohr, as far as division of labor, I would prefer if you update the mic components & BOM stuff. I can do the silkscreen and part placement (and probably the rerouting too)

**Comment by cnlohr** [comment]
- [x] SAO movement.
- [x] Make Switch flush with board.

**Comment by cnlohr** [comment]
- [x] Move microphone to where old mic was.

**Comment by cnlohr** [comment]
- [x] Try to make the switch go right up next to the USB.

**Comment by AEFeinstein** [comment]
> SAO movement.

"Move SAO out from under kidney, flip to front of Swadge" in the ticket description

> Make Switch flush with board.

"Move power switch up to not hang over the board so much (flush)" in the ticket description

> Move microphone to where old mic was.

"Pick a microphone, scrap the other, move it to original location" in the ticket description

> Try to make the switch go right up next to the USB.

Was this feedback from the jam?

**Comment by cnlohr** [comment]
Only thing I think I need to answer is that yes, switch up was feedback from jam.  @AEFeinstein are you OK with that?  Looks like you already fixed it. You did fix it right?  I'm not crazy?

**Comment by AEFeinstein** [comment]
I moved the switch up so that the arm doesn't hang over the edge at all. I didn't relocate the switch to the top of the board, next to the USB port. You're not crazy

**Comment by cnlohr** [comment]
- [x] Switch LED footprints on left side to match right side.
 - [x] Move SAO to above D-pad OR maybe to right if not possible.
 - [x] Move Start/Select in just a tiny bit.
 - [x] Flip SAO potentially.
 - [x] 0-ohm the touch pads
 - [x] Select+Start = Back
