### ISSUE TITLE
Fix SW9 silkscreen + Move ring

### ISSUE THREAD

**Issue by cnlohr** [AEFeinstein/Swadge-S2-Devkit#6]
Says in title.

This is post EV2

**Comment by AEFeinstein** [comment]
What's wrong with SW9? BT1 needs to be reset to have (-) be aligned

**Comment by cnlohr** [comment]
Aaah ok

Plx assign to me.  I have the semaphore.  I am currently balancing both branches. I'd rather not make mods until the orders are in.

**Comment by AEFeinstein** [comment]
Reassigned. Have fun balancing the branches. Kicad files aren't that git friendly 😟

As a general note, when you're done with branches (either merged or abandoned), remember to delete them!

**Comment by cnlohr** [comment]
SW9 was resolved at some point..
Ring looks "too low" based on screen silk.

<div style="font-family:Verdana,Geneva,sans-serif"><span class="im">
<p>Dear Charles,</p>
<p>Thanks for your feedback!</p>
</span><p>I understand the situation of your production prototypes, sorry for your confuse!</p>
<p>I will provide the old ones (yellow) which are measured to be 32mm,</p>
<p>please design your production prototypes according to this 32mm length,</p><span class="im">
<p>Have a nice day!</p></span></div></div></div></div>

**Comment by AEFeinstein** [comment]
> SW9 was resolved at some point.

OK, I'm not going crazy

> Ring looks "too low" based on screen silk.

I fixed that in the `more-cad` branch when doing Dac's render. PR here: https://github.com/AEFeinstein/Swadge-S2-Devkit/pull/7
