### ISSUE TITLE
Need replacement LCD

### ISSUE THREAD

**Issue by camprevail** [AEFeinstein/Swadge-S2-Devkit#8]
Hi, I cracked my 2023 swadge LCD and I searched through this repo but I can't find the LCD model used so I can replace it. Can you help me out?

**Comment by AEFeinstein** [comment]
The info is buried in the BOM in the release zip, but it's a RB017A1505A from http://www.ronboe.com/ or https://ronboelectronics.en.made-in-china.com/ (I'm not sure why they have two websites). The part isn't listed, but if you email you may be able to get a sample. We bought a large quantity and I'm not sure how they feel about single orders.
